#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
usage() { echo "Usage: ${0} [--tag <string>] [--push]" 1>&2; exit 1; }
TAG="latest"
PUSH="false"
while [ $# -gt 0 ]; do
  case "$1" in
    "--tag")
      if [ $# -le 2 ]; then echo "aaa"; usage; fi
      TAG="$2"
      shift 2;;
    "--push")
      PUSH="true"
      shift;;
    *) echo "bbb"; usage;;
  esac
done
docker build "${DIR}" -t "pjvleeuwen/drupal-dtap:${TAG}"
if [ "${PUSH}" = "true" ]; then
  docker push "pjvleeuwen/drupal-dtap:${TAG}"
fi

